**Уровень 0**  
Придумайте матрицы, которые обладают следующими свойствами:  
a) диагональная, ортогональная, но не единичная(!):  
b) верхнетреугольная, ортогональная:  
c) нижнетреугольная, ортогональная:  
d) матрица, у которой определитель = 1, и все элементы не равны 0:  

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!  

In [2]:
import numpy as np

In [3]:
a = np.array([[1, 0], [0, -1]])
print(f"a) диагональная, ортогональная, но не единичная:\n{a}\n")
print(f"При проверке транспонированием должна получиться единичная матрица:\n{a @ a.transpose()}")

a) диагональная, ортогональная, но не единичная:
[[ 1  0]
 [ 0 -1]]

При проверке транспонированием должна получиться единичная матрица:
[[1 0]
 [0 1]]


In [8]:
# b) верхнетреугольная, ортогональная
# c) нижнетреугольная, ортогональная
# один ответ - диагональная матрица из 1 или -1

b = np.array([[-1, 0], [0, -1]])
print(f"верхнетреугольная и одновременно нижнетреугольная, ортогональная\n{b}\n")
print(f"При проверке транспонированием должна получиться единичная матрица:\n{b @ b.transpose()}")

верхнетреугольная и одновременно нижнетреугольная, ортогональная
[[-1  0]
 [ 0 -1]]

При проверке транспонированием должна получиться единичная матрица:
[[1 0]
 [0 1]]


In [9]:
# матрица, у которой определитель = 1, и все элементы не равны 0
d = np.array([[3, 2], [4, 3]])
print(d)
print(f"Детерминант: {np.linalg.det(d)}")

[[3 2]
 [4 3]]
Детерминант: 1.0


**Задание 2**  
Найдите собственные значения и собственные вектора матриц:  
m = np.array([[2, 2],  
[1, 3]])  

In [19]:
m = np.array([[2, 2],
[1, 3]])
print(m)
print(f"Собственные значения: {np.linalg.eig(m)[0][0]} и {np.linalg.eig(m)[0][1]}")
print(f"Собственные векторы:\n {np.linalg.eig(m)[1]}")
# т.е. собственные значения 1 и 4, а собственные вектора-столбцы (1, 1) и (2, -1)

[[2 2]
 [1 3]]
Собственные значения: 1.0 и 4.0
Собственные векторы:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
