**Уровень 0:**  
a) Создайте матрицу 3 на 3, заполненную числами от 1 до 9

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

b) Прибавьте к ней матрицу с единицами на диагонали

In [23]:
b = a + np.eye(3)
b

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

c) Умножьте полученную матрицу на вектор (1, 2, 3)

In [10]:
v = np.array([1, 2, 3])
c = np.dot(b, v)
c

array([15., 34., 53.])

d) Посчитайте обратную матрицу к полученной матрице

In [24]:
d = np.linalg.inv(b)
d

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [22]:
e = np.array([[-6, -2, 3], [-1, .5, 0], [5, 1, -2]])    # Проверим матрицу с округлёнными числами из пред. примера
e @ b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Уровень 1:**  
Дан объект в 2d пространстве:  
import numpy as np  
import matplotlib.pyplot as plt  

A = [
[-100, -100, 1],
[-100, 100, 1],
[100, 100, 1],
[0, 0, 1],
[100, -100, 1],
[-100, -100, 1]
]  
A = np.array(A)  
x = A[:,0]  
y = A[:,1]  
plt.plot(x, y)  
plt.ylim([-200, 200])  
plt.xlim([-200, 200])  

При помощи матричных операций выполните:
Уменьшить объект в два раза.
Повернуть на 130 градусов.
Отразить объект относительно прямой y=x
Выполнить смещение объекта и масштабирование (применить 2 матрицы трансформаций). Смещение на (200, 300) и масштабирование на (0.5, 1,2)